/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeamExtensionRouteImport } from './routes/team-extension'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as HowWeWorkRouteImport } from './routes/how-we-work'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AiSolutionsRouteImport } from './routes/ai-solutions'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminEditorRouteImport } from './routes/admin.editor'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as AdminContentSectionRouteImport } from './routes/admin.content.$section'
import { Route as AdminCollectionsTypeRouteImport } from './routes/admin.collections.$type'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media.$'
import { Route as AdminCollectionsTypeIdRouteImport } from './routes/admin.collections.$type.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamExtensionRoute = TeamExtensionRouteImport.update({
  id: '/team-extension',
  path: '/team-extension',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeWorkRoute = HowWeWorkRouteImport.update({
  id: '/how-we-work',
  path: '/how-we-work',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSolutionsRoute = AiSolutionsRouteImport.update({
  id: '/ai-solutions',
  path: '/ai-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InsightsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditorRoute = AdminEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentSectionRoute = AdminContentSectionRouteImport.update({
  id: '/content/$section',
  path: '/content/$section',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsTypeRoute = AdminCollectionsTypeRouteImport.update({
  id: '/collections/$type',
  path: '/collections/$type',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollectionsTypeIdRoute = AdminCollectionsTypeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCollectionsTypeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-solutions': typeof AiSolutionsRoute
  '/cases': typeof CasesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/gdpr': typeof GdprRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team-extension': typeof TeamExtensionRoute
  '/terms': typeof TermsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/editor': typeof AdminEditorRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/users': typeof AdminUsersRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/admin/collections/$type': typeof AdminCollectionsTypeRouteWithChildren
  '/admin/content/$section': typeof AdminContentSectionRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/admin/collections/$type/$id': typeof AdminCollectionsTypeIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-solutions': typeof AiSolutionsRoute
  '/cases': typeof CasesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/gdpr': typeof GdprRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/industries': typeof IndustriesRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team-extension': typeof TeamExtensionRoute
  '/terms': typeof TermsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/editor': typeof AdminEditorRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/users': typeof AdminUsersRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/admin/collections/$type': typeof AdminCollectionsTypeRouteWithChildren
  '/admin/content/$section': typeof AdminContentSectionRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/admin/collections/$type/$id': typeof AdminCollectionsTypeIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-solutions': typeof AiSolutionsRoute
  '/cases': typeof CasesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/gdpr': typeof GdprRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team-extension': typeof TeamExtensionRoute
  '/terms': typeof TermsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/editor': typeof AdminEditorRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/users': typeof AdminUsersRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/admin/collections/$type': typeof AdminCollectionsTypeRouteWithChildren
  '/admin/content/$section': typeof AdminContentSectionRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/admin/collections/$type/$id': typeof AdminCollectionsTypeIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ai-solutions'
    | '/cases'
    | '/contact'
    | '/cookies'
    | '/gdpr'
    | '/how-we-work'
    | '/industries'
    | '/insights'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/team-extension'
    | '/terms'
    | '/admin/audit'
    | '/admin/editor'
    | '/admin/login'
    | '/admin/media'
    | '/admin/users'
    | '/insights/$slug'
    | '/admin/'
    | '/insights/'
    | '/admin/collections/$type'
    | '/admin/content/$section'
    | '/api/public/contact'
    | '/admin/collections/$type/$id'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-solutions'
    | '/cases'
    | '/contact'
    | '/cookies'
    | '/gdpr'
    | '/how-we-work'
    | '/industries'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/team-extension'
    | '/terms'
    | '/admin/audit'
    | '/admin/editor'
    | '/admin/login'
    | '/admin/media'
    | '/admin/users'
    | '/insights/$slug'
    | '/admin'
    | '/insights'
    | '/admin/collections/$type'
    | '/admin/content/$section'
    | '/api/public/contact'
    | '/admin/collections/$type/$id'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ai-solutions'
    | '/cases'
    | '/contact'
    | '/cookies'
    | '/gdpr'
    | '/how-we-work'
    | '/industries'
    | '/insights'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/team-extension'
    | '/terms'
    | '/admin/audit'
    | '/admin/editor'
    | '/admin/login'
    | '/admin/media'
    | '/admin/users'
    | '/insights/$slug'
    | '/admin/'
    | '/insights/'
    | '/admin/collections/$type'
    | '/admin/content/$section'
    | '/api/public/contact'
    | '/admin/collections/$type/$id'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiSolutionsRoute: typeof AiSolutionsRoute
  CasesRoute: typeof CasesRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  GdprRoute: typeof GdprRoute
  HowWeWorkRoute: typeof HowWeWorkRoute
  IndustriesRoute: typeof IndustriesRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamExtensionRoute: typeof TeamExtensionRoute
  TermsRoute: typeof TermsRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-extension': {
      id: '/team-extension'
      path: '/team-extension'
      fullPath: '/team-extension'
      preLoaderRoute: typeof TeamExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-work': {
      id: '/how-we-work'
      path: '/how-we-work'
      fullPath: '/how-we-work'
      preLoaderRoute: typeof HowWeWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-solutions': {
      id: '/ai-solutions'
      path: '/ai-solutions'
      fullPath: '/ai-solutions'
      preLoaderRoute: typeof AiSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/editor': {
      id: '/admin/editor'
      path: '/editor'
      fullPath: '/admin/editor'
      preLoaderRoute: typeof AdminEditorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/$section': {
      id: '/admin/content/$section'
      path: '/content/$section'
      fullPath: '/admin/content/$section'
      preLoaderRoute: typeof AdminContentSectionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections/$type': {
      id: '/admin/collections/$type'
      path: '/collections/$type'
      fullPath: '/admin/collections/$type'
      preLoaderRoute: typeof AdminCollectionsTypeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collections/$type/$id': {
      id: '/admin/collections/$type/$id'
      path: '/$id'
      fullPath: '/admin/collections/$type/$id'
      preLoaderRoute: typeof AdminCollectionsTypeIdRouteImport
      parentRoute: typeof AdminCollectionsTypeRoute
    }
  }
}

interface AdminCollectionsTypeRouteChildren {
  AdminCollectionsTypeIdRoute: typeof AdminCollectionsTypeIdRoute
}

const AdminCollectionsTypeRouteChildren: AdminCollectionsTypeRouteChildren = {
  AdminCollectionsTypeIdRoute: AdminCollectionsTypeIdRoute,
}

const AdminCollectionsTypeRouteWithChildren =
  AdminCollectionsTypeRoute._addFileChildren(AdminCollectionsTypeRouteChildren)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminEditorRoute: typeof AdminEditorRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCollectionsTypeRoute: typeof AdminCollectionsTypeRouteWithChildren
  AdminContentSectionRoute: typeof AdminContentSectionRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminEditorRoute: AdminEditorRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCollectionsTypeRoute: AdminCollectionsTypeRouteWithChildren,
  AdminContentSectionRoute: AdminContentSectionRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface InsightsRouteChildren {
  InsightsSlugRoute: typeof InsightsSlugRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSlugRoute: InsightsSlugRoute,
  InsightsIndexRoute: InsightsIndexRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AiSolutionsRoute: AiSolutionsRoute,
  CasesRoute: CasesRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  GdprRoute: GdprRoute,
  HowWeWorkRoute: HowWeWorkRoute,
  IndustriesRoute: IndustriesRoute,
  InsightsRoute: InsightsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamExtensionRoute: TeamExtensionRoute,
  TermsRoute: TermsRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
