// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    let token: string | undefined
    try {
      const { data } = await supabase.auth.getSession()
      token = data.session?.access_token
      // Race-condition fallback: if the Supabase client hasn't hydrated the
      // session from storage yet (returns null on first read after a hard
      // refresh), try refreshing once before giving up.
      if (!token) {
        const { data: refreshed } = await supabase.auth.refreshSession()
        token = refreshed.session?.access_token
      }
    } catch {
      // ignore – will fall through with no token
    }
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
